- .kube.dev.yaml
- config.js
- lib/api.js
- package-lock.json
- package.json
This will eventually become a workflow API that takes tasks in one end, performs tasks, and then eventually resolves.
For now just proxy the change requests directly to the resolver.
> Replace service with simple proxy to resolver service

- .kube.dev.yaml
- config.js
- lib/api.js
- lib/queue.js
- package-lock.json
- package.json
At the moment there's no middle of workflow, so we're just pushing every message that is POSTed to the API to the SQS queue, but once there is a middle then this will represent the end.
> Push messages to SQS at "end" of workflow

- .kube.dev.yaml
- config.js
- lib/api.js
- package-lock.json
- package.json
For now the business rules are the same as they were before - i.e. there's no business rules - everything is still instantly resolved.
BUT there is now an interface into which we can apply hook logic to divert different change-requests to different statuses and resolve at different places in the workflow.
> First implementation of workflow business rules

- config.js
- lib/api.js
- lib/errors/index.js
- lib/errors/timeout.js
- lib/hooks/create/index.js
- lib/hooks/resolve/index.js
- package-lock.json
- package.json
* Added polling method which checks changelog for resolved messageId
* Throw error on timeout
> Poll changelog for instantly resolved tasks

- lib/api.js
- lib/hooks/create/index.js
- lib/hooks/resolve/index.js
When a PIL change request is submitted with the `grant` action, set the case status to `ntco-endorsement`.
... also brought in some of the changes @joefitter made in #20.
> AS-754: set case status to ntco-endorsement when PIL submitted to NTCO

- lib/api.js
- lib/flow/index.js
- lib/flow/pil.js
- lib/hooks/create/index.js
- lib/hooks/create/pil.js
- lib/middleware/case-decorator.js
- lib/middleware/exclude-auto-resolved.js
- package-lock.json
- package.json
- test/.eslintrc
- test/flow.js
When a list of tasks (cases) is fetched from the taskflow database, we need to provide some extra data to make them actually useful in the frontend.
> Decorate tasks with establishments, profiles, and next steps

- knexfile.js
- package-lock.json
- package.json
- seeds/data/cases.json
- seeds/index.js
- seeds/tables/cases.js
I just added some basic data to cases to be able to test datatable on user dashboard, @wheelsandcogs not sure if you'd agree how I structured the seed folder - it is based on asl-schema, but please do let me know your thoughts.
> Add seeds for cases

- package.json
- seeds/taskflow/cases.js
> * Enable snake mapper when running seeds

- lib/api.js
- lib/errors/bad-request.js
- lib/flow/index.js
- lib/hooks/validate/payload.js
- lib/hooks/validate/status.js
- package-lock.json
- package.json
~Needs https://github.com/UKHomeOffice/taskflow/pull/19 merging first so we can bump the version here.~
Done.
> Check status changes are valid for the flow and contain the correct payload

- lib/query-builders/admin.js
- lib/query-builders/index.js
- lib/query-builders/ntco.js
Establishment admin users should be able to see any tasks relating to their establishment.
> Add query builder for establishment admin users

- lib/decorators/index.js
- lib/flow/get-next-steps-for-user.js
- lib/flow/index.js
- lib/flow/status.js
- lib/hooks/validate/status.js
- lib/query-builders/inspector.js
- lib/query-builders/licensing-officer.js
- package-lock.json
- package.json
- seeds/data/cases.json
- test/data/tasks.js
- test/helpers/taskflow-db.js
- test/helpers/workflow.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
- test/integration/task-lists/ntco.js
- test/integration/tasks/applicant.js
- test/integration/tasks/establishment-admin.js
- test/integration/tasks/ntco.js
Waiting on https://github.com/UKHomeOffice/taskflow/pull/25
We should also use a similar method to validate case status changes.
> Change the task actions depending upon who is viewing the task

- lib/api.js
- lib/flow/index.js
- lib/hooks/create/unique.js
- lib/hooks/resolve/index.js
- package-lock.json
- package.json
- test/data/default.js
- test/data/ids.js
- test/data/tasks.js
- test/helpers/workflow.js
- test/integration/tasks/applicant.js
Before creating a new task, check if any existing tasks are open for that object id, and if any exist reject the task creation.
> Ensure a maximum of one open task per data entity

- lib/api.js
- lib/decorators/activity-log.js
- lib/decorators/index.js
- lib/decorators/metadata.js
- package-lock.json
- package.json
Decorate the "changedBy" profile id with the actual profile data so we don't have to request it later.
Waiting on https://github.com/UKHomeOffice/taskflow/pull/29 and a bump to taskflow
> Add profile data to the activity log "changedBy" props

- lib/api.js
- lib/hooks/update-data/index.js
- lib/hooks/update-data/project.js
Also moved update-data hook to pre-status changes, this is so the status logs contain the new data
> added project update hook to set version awerb and authority properties

- lib/query-builders/index.js
- package-lock.json
Sort by date oldest first for most lists except completed which is newest first.
> Add default sort orders to task lists

- lib/decorators/metadata.js
- lib/hooks/meta/index.js
we were decorating the case with modelData at the point of request. It is more useful to get the status at the point of application
> Use modelData from point of submission

- lib/hooks/meta/default.js
- lib/hooks/meta/index.js
- lib/hooks/meta/pil.js
- lib/hooks/meta/profile.js
- lib/hooks/resolve/index.js
- package-lock.json
- package.json
Allows a more explicit setting of the fields we're interested in without risking overwriting other data points.
There's a couple of places in the `update-data` hooks where it goes a level deeper that I wasn't quite prepared to tamper with right now so those have been left as they were.
> Use patch for updating models

- lib/hooks/create/project.js
insta resolve project updates if the status is inactive, send to inspectorate if not
> Amend PPL holder

- lib/hooks/create/project.js
- lib/hooks/resolve/index.js
When a user submits a task to grant a project then it should also find the most recent draft and mark that as complete.
> Mark project version as submitted when creating a project grant

- lib/api.js
- lib/decorators/deadline.js
- lib/router/metrics.js
- package-lock.json
- package.json
- test/helpers/asl-db.js
Exposes an endpoint to fetch a list of tasks that have been resolved in a defined timeframe.
Exposes only the task type, and some basic metadata about the number of iterations to complete and the time to complete.
> Add metrics endpoint to workflow

- lib/hooks/create/project.js
~Waiting on https://github.com/UKHomeOffice/asl-resolver/pull/99~
> Add hook for revoking a ppl

- lib/api.js
- lib/hooks/recall/index.js
* Duplicate returned hooks on recalled
* Duplicate recalled hooks on returned
* Only fork on project grant
> Recall and returned

- lib/query-builders/index.js
- test/data/tasks.js
- test/helpers/assert-task-order.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
- test/integration/task-lists/ntco.js
- test/integration/tasks-for-model/index.js
Make the task list ordering match the expected requirements for each user type and progress status.
> Task list ordering

- lib/api.js
- lib/flow/index.js
- lib/flow/status.js
- lib/hooks/auto-forward/index.js
- lib/hooks/create/pil.js
- lib/hooks/create/project.js
- lib/hooks/endorsed/index.js
- lib/hooks/validate/status.js
- lib/query-builders/admin.js
- lib/query-builders/endorse-ppl.js
- lib/query-builders/index.js
- lib/query-builders/inspector.js
- lib/query-builders/licensing-officer.js
- lib/query-builders/ntco.js
- lib/util.js
- test/data/tasks.js
- test/flow.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/establishment-admin.js
- test/integration/tasks/establishment-admin.js
- test/integration/tasks/ntco.js
* Added new statuses with-admin and admin-endorsed
* admin-endorsed auto-forwards to with-inspectorate
* if applicant is admin, project grant/update go to inspectorate, or to with-admin if not
> Feature - Admin endorse PPL

- lib/decorators/filter-comments.js
Allow easier detection of comment ownership on the client.
> Add an "isMine" property to comments

- lib/hooks/create/establishment.js
~Waiting on resolver PR https://github.com/UKHomeOffice/asl-resolver/pull/112~
> Add create hook for establishments

- lib/hooks/create/profile.js
- package-lock.json
- package.json
- test/integration/profile/update.js
If a task is a `profile.update` which only touches the email address then don't send to ASRU for approval.
> Autoresolve email changes

- lib/hooks/edit-and-resubmit/index.js
- test/unit/hooks/edit-and-resubmit/index.js
* Task updates should not be merged else array items cannot be removed
> Bugfix - dont merge arrays when updating data

- lib/hooks/create/establishment.js
- test/data/default.js
- test/integration/establishment/grant.js
~Waiting on https://github.com/UKHomeOffice/asl-resolver/pull/119~
> Handle grant PEL tasks

- lib/hooks/create/role.js
- test/data/default.js
- test/helpers/asl-db.js
- test/unit/hooks/create/role.js
* if role it holc, autoresolve
* if changedBy is licensing autoresolve
* if changedBy is asru send to licensing
* if changedBy is not asru send to inspectorate
> Feature - asru updating roles

- lib/hooks/create/index.js
- lib/hooks/create/place.js
- test/integration/tasks/applicant.js
- test/unit/hooks/create/place.js
* Check changedBy when a place task is created
* Send to inspector if not-asru
* Send to licensing if inspector
* Autoresolve if licensing
> Feature - Added place task create hook

- lib/hooks/create/index.js
- lib/hooks/meta/index.js
And ignore metadata hook because there's no metadata to add
> Autoresolve fee waiver models

- lib/hooks/create/unique.js
- package-lock.json
- package.json
- test/integration/fee-waiver/index.js
Skips the uniqueness check on the model id is the model type is a fee waiver so that waivers are not blocked by open PIL tasks.
> Allow Fee Waiver tasks to be created if PIL task is open

- lib/hooks/meta/index.js
- lib/hooks/recall/index.js
- package-lock.json
- package.json
- test/integration/fee-waiver/index.js
- test/integration/pil/transfer.js
- test/integration/profile/update.js
- test/integration/tasks/applicant.js
* On create add asruInitiated flag to task so a task can be identified as created by asru and filtered out of relevant lists
> Feature - add asruInitiated flag to task

- lib/hooks/create/establishment.js
- lib/router/model-tasks.js
- test/data/default.js
- test/data/profiles.js
- test/integration/establishment/revoke.js
Waiting on https://github.com/UKHomeOffice/asl-resolver/pull/131
> Establishment revoke

- lib/hooks/create/unique.js
Reverts UKHomeOffice/asl-workflow#215
> Revert "dont perform uniqueness check if updating billing info"

- lib/decorators/deadline.js
- package-lock.json
- package.json
- test/unit/decorators/deadline.js
This wasn't being calculated correctly in cases where the PPL application had been submitted multiple times. Make sure we're using the correct submission date.
> Fix deadline calculation for PPL applications

- lib/flow/index.js
- lib/hooks/create/project.js
- lib/hooks/endorsed/index.js
- lib/hooks/endorsed/project.js
- lib/messager/index.js
- test/data/default.js
- test/data/ids.js
- test/integration/project/transfer.js
- test/integration/project/update-issue-date.js
- test/unit/hooks/endorsed/project.js
* Added to endorse hook for projects - if transfer then update task establishmentId
* Added transfer to create hook to follow same path as grant tasks
> PPL - change establishment

- lib/decorators/deadline/index.js
- lib/hooks/create/unique.js
- lib/query-builders/index.js
- lib/router/metrics/index.js
- lib/router/model-tasks.js
- lib/router/profile-tasks.js
- lib/router/tasks.js
- package-lock.json
- package.json
- test/helpers/taskflow-db.js
- test/unit/decorators/deadline.js
- test/unit/hooks/recall/index.js
Mostly involves renaming `Case` to `Task`
> Update taskflow to latest

- lib/hooks/create/project.js
~Waiting on https://github.com/UKHomeOffice/asl-resolver/pull/140~
> Allow update of project stub licence number

- lib/hooks/create/unique.js
- package-lock.json
- package.json
- test/data/ids.js
- test/data/tasks.js
- test/integration/hooks/unique.js
- test/integration/profile-tasks/index.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/establishment-admin.js
* resubmitted transfers are sent as grant tasks - allow this in uniqueness check
* bumped taskflow with activity log createdAt fix
> Bugfix - Grant/transfer

- lib/hooks/update-action/index.js
- test/integration/project/transfer.js
* added to and from establishment meta to task if transfer
> Feature - transfer meta

- lib/hooks/meta/index.js
It's liable to be massive, and overwhelm activity logs.
> Don't save project version modelData

- lib/decorators/task-type.js
- lib/flow/index.js
- lib/flow/status.js
- lib/hooks/create/pil.js
- lib/hooks/endorsed/index.js
- lib/hooks/endorsed/pil.js
- lib/query-builders/ntco.js
- test/data/default.js
- test/data/ids.js
- test/integration/pil/review.js
* added create hook for review - autoresolve if ntco, set to awaitingEndorsement if not
* updated ntco query builder to include review pils
* added pil review hook to resolve task
> Feature - PIL review

- lib/query-builders/applicant.js
- test/data/tasks.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
* don't blacklist asru tasks if user is asru
> Bugfix - ASRU can be applicant

- lib/router/metrics/tasks.js
This allows segmenting data by date in clients that consume this endpoint
> Include updatedAt data in metrics response

- lib/flow/get-next-steps-for-user.js
- lib/hooks/create/pil.js
- test/data/default.js
- test/data/ids.js
- test/data/profiles.js
- test/integration/pil/transfer.js
* Added pil.transfer to whitelist of actionable asru initiated tasks
* Fixed logic so only licence holder or asru can init transfer
* Updated tests to use logged in user
> Bugfix - NTCO cannot action ASRU xfer

- lib/hooks/create/index.js
* added create hook to autoresolve creating and deleting profiles from projects
> Feature - added projectProfile hook

- lib/hooks/create/pil.js
* previously this would autoresolve and not leave a task behind
> Bugfix - resolve pil grant if asru

- lib/api.js
- lib/decorators/continuation.js
- lib/decorators/index.js
- lib/hooks/create/project.js
- lib/hooks/update-action/index.js
- test/data/default.js
- test/data/ids.js
- test/data/profiles.js
- test/data/tasks.js
- test/integration/hooks/unique.js
- test/integration/project/continuation.js
- test/integration/project/transfer.js
- test/integration/task-lists/establishment-admin.js
- test/unit/decorators/filter-comments.js
* Added create hook for project grant/transfer to add continuation data to task if found in licence
* Added decorator to add continuation to task if undefined on project grant/transfer (in flight amendments)
> Feature - continuation as structured data

- lib/api.js
* update data was being set after create so version was undefined in create hooks
> Bugfix - set version on create

- lib/hooks/create/unique.js
- package-lock.json
- package.json
- test/helpers/taskflow-db.js
- test/helpers/workflow.js
- test/integration/establishment/grant.js
If there's an open amendment to the establishment details still allow the establishment to apply to be granted. This is for consistency with other PEL changes (places, roles, etc) that do not block the application.
> Allow an establishment grant to be opened alongside other establishment tasks

- lib/hooks/create/place.js
- package-lock.json
- package.json
- test/data/default.js
- test/data/ids.js
- test/helpers/asl-db.js
- test/integration/place/update.js
~Needs
https://github.com/UKHomeOffice/asl-schema/pull/313
https://github.com/UKHomeOffice/asl-resolver/pull/155~
> Autoresolve role updates on places

- lib/hooks/meta/index.js
- lib/hooks/meta/project.js
- test/integration/project/update-licence-holder.js
* Added hook to set subject as licence holder. If create then set to provided id
> PPL licence holder subject

- config.js
- lib/messager/s3/index.js
Dependent on https://github.com/UKHomeOffice/asl-resolver/pull/157 so that should go first
> Encrypt data stored in s3

- lib/flow/status.js
- lib/hooks/create/establishment.js
- lib/hooks/create/pil.js
- lib/hooks/create/place.js
- lib/hooks/create/role.js
- lib/util.js
- test/integration/establishment/conditions.js
- test/integration/establishment/revoke.js
- test/integration/place/update.js
- test/unit/hooks/create/place.js
- test/unit/hooks/create/role.js
* Updated autoresolved to resolved for LO tasks
* use resolved for assigning holc, and roles to places
> Feature - resolved tasks

- lib/hooks/model-data/index.js
- package-lock.json
- package.json
* updated schemea with join roles method
* use join roles when adding modelData
> Bugfix - place roles

- lib/api.js
- lib/hooks/submission-meta/index.js
- test/data/default.js
- test/data/ids.js
- test/data/tasks.js
- test/integration/pil/grant.js
* Added new hook to attach training an exemptions to task on submission and resubmission
> Feature - pil training on submission

- lib/hooks/create/index.js
- lib/hooks/submission-meta/index.js
- package-lock.json
- package.json
- test/data/default.js
- test/data/ids.js
- test/integration/pil/grant.js
* Removed exemptions, updated structure of certificates
> Feature - training in profiles

- lib/api.js
- lib/decorators/index.js
- lib/decorators/normalise-training.js
Added decorator to nomalise certificates/exemptions of in flight tasks
> Bugfix - normalise training

- lib/api.js
- lib/decorators/index.js
- lib/decorators/training-pil-meta.js
- lib/flow/get-next-steps-for-user.js
- lib/hooks/create/index.js
- lib/hooks/create/training-pil.js
- lib/hooks/discard/index.js
- lib/hooks/endorsed/index.js
- lib/hooks/endorsed/training-pil.js
- lib/hooks/model-data/index.js
- lib/query-builders/admin.js
- lib/query-builders/endorse-ppl.js
- lib/query-builders/filter-to-establishments.js
- lib/query-builders/index.js
- lib/query-builders/ntco.js
- lib/router/related-tasks.js
- lib/util.js
- package-lock.json
- package.json
- test/data/default.js
- test/data/ids.js
- test/data/tasks.js
- test/helpers/asl-db.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/ntco.js
- test/unit/hooks/create/training-pil.js
- test/unit/hooks/endorsed/training-pil.js
* Added create hook for trainingPil - creates trainingPil  and sends for endorsement
* Added endorsed hook - to est-b if existing pil elsewhere
* Added decorator to include trainingPil status
* Added training pil related tasks list
> Feature - cat e pils

- bin/deadline-has-passed
This should be set to run after midnight each night, to flag any tasks where the deadline has passed.
> Deadline passed checker

- lib/flow/index.js
* The UI for this needs to be built
> Bugfix - training pil, remove edit and resubmit

- lib/decorators/training-pil-meta.js
- lib/hooks/create/training-pil.js
- test/unit/hooks/create/training-pil.js
`task.data.subject` was not being set for Training PIL tasks.
> Add profile names to PIL training tasks in tasklist

- seeds/data/cases.json
Adds some completed tasks for the PIL E applications that exist in the "normal" seeds.
> Add task seeds for PIL Es

- lib/hooks/resolve/index.js
* When a ppl grant task is approved, patch the licenceNumber to modelData so it can be shown in task lists
> Feature - PPL application licence number

- lib/decorators/task-type.js
- lib/hooks/create/project.js
- lib/hooks/endorsed/project.js
- lib/hooks/recall/index.js
- lib/hooks/resolve/index.js
- lib/hooks/update-data/project.js
- lib/middleware/skip-workflow.js
- package-lock.json
- package.json
- test/unit/decorators/task-type.js
- test/unit/hooks/create/project.js
- test/unit/hooks/endorsed/project.js
- test/unit/hooks/recall/index.js
- test/unit/hooks/resolve/index.js
* Added actions for patch fork and grant for RA
> Feature - RA

- lib/hooks/create/project.js
- test/unit/hooks/create/project.js
These should not need to be reviewed or approved by an inspector or licensing officer, so resolve immediately on submission.
> Resolve RA submissions if submitted by an ASRU user

- lib/flow/status.js
- lib/hooks/create/establishment.js
- package-lock.json
- package.json
- test/unit/hooks/create/establishment.js
* Resolve update-cjsm task if from asru
> Feature - CJSM

- lib/hooks/create/index.js
- lib/hooks/resolve/index.js
- lib/middleware/skip-workflow.js
- package-lock.json
- package.json
* Skip workflow for rop create and update, and proc create update and delete.
* Respond with id when new rop created
* Bumped schema with rop models
> Feature - ROPS

- lib/hooks/create/index.js
- lib/hooks/create/rop.js
- lib/middleware/skip-workflow.js
* Leave resolved task for rop submission/unsubmission
> Feature - rop submit/unsubmit

- lib/hooks/discard/index.js
needs https://github.com/UKHomeOffice/asl-resolver/pull/215
> Tell resolver to delete the RA when ra task is discarded

- lib/router/related-tasks.js
* Include rop tasks in related tasks for project
> Feature - include rops in related activity

- lib/decorators/activity-log.js
- lib/decorators/metadata.js
- package-lock.json
- package.json
- test/helpers/asl-db.js
* bumped taskflow with task assignment
* added assigned tasks to activity log
* lookup assigned to profile in decorator
> Feature - task assignment

- lib/query-builders/filters/index.js
- lib/query-builders/filters/my-tasks.js
- lib/query-builders/inspector.js
- lib/query-builders/licensing-officer.js
- package-lock.json
- package.json
- test/data/tasks.js
- test/helpers/assert-tasks.js
- test/integration/related-tasks/establishment.js
- test/integration/related-tasks/index.js
- test/integration/related-tasks/pil.js
- test/integration/related-tasks/profile-touched.js
- test/integration/related-tasks/profile.js
- test/integration/related-tasks/project.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/asru.js
- test/integration/task-lists/error-states.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
- test/integration/task-lists/ntco.js
If a user is an LO or inspector then add any tasks assigned to them to their "my tasks" list, and exclude tasks assigned to other users.
> Include assigned tasks in LO and inspector "my tasks"

- lib/api.js
- lib/hooks/unassign/index.js
- package-lock.json
- package.json
If a user has a task assigned and moves the task to a new status then remove the existing assignment. This ensures that the task will appear correctly in the downstream user's "My tasks" list.
> Unassign tasks when processed

- lib/hooks/create/unique.js
* Allow duplicate task for project update is status is inactive
> Feature - change licence holder - ppl draft

- lib/hooks/search/index.js
Send a request to search to re-index the establishment if the roles on the PEL are updated.
> Re-index PEL when roles are changed

- lib/api.js
* Only unassign task if referred to inspector from licensing
> Tweak - dont unassign on process

- lib/decorators/next-steps.js
- lib/flow/get-next-steps-for-user.js
- lib/flow/index.js
- lib/flow/status.js
- lib/hooks/auto-forward/index.js
- package-lock.json
- package.json
- test/data/default.js
- test/data/ids.js
- test/data/tasks.js
- test/integration/project/rejection.js
- test/integration/related-tasks/profile-touched.js
- test/integration/task-lists/asru.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
* Added recovered status, only usable by asru admin, autoforwards to with-inspectorate
* Dont include recovered in next steps - (decorator)
> Feature - recovered status

- lib/api.js
- lib/decorators/deadline/complete-and-correct.js
- lib/decorators/index.js
- lib/decorators/normalise-meta.js
- lib/hooks/endorsed/project.js
- lib/hooks/update-data/project.js
- test/unit/hooks/endorsed/project.js
* Added decorator to map Yes yes no values to correct booleans
> Bugfix - added truthy decorator

- lib/query-builders/filters/my-tasks.js
- test/data/tasks.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
Since affiliated establishments are no longer a thing.
> Remove tasks for associated establishments from ASRU "My Tasks"

- lib/api.js
- lib/decorators/index.js
- lib/decorators/place-metadata.js
This allows the UI to easily change without reproducing all the same logic there.
> Add marker to task if only roles changed on a place amendment

- lib/router/related-tasks.js
- package-lock.json
- package.json
- test/data/activity.js
- test/data/ids.js
- test/data/tasks.js
- test/integration/related-tasks/profile-touched.js
This will include all tasks currently assigned to a particular ASRU user in the "Related tasks" section of their profile.
Also prevent a task from showing as related if assigning it to another user.
> Add assignment to related tasks query

- seeds/data/internal-deadline-cases.js
- seeds/helpers/create-task.js
- seeds/tables/cases.js
* Allow `makeTask` function to include a date to backdate seed tasks
* Add `activity` helper to append additional activity to seeded tasks
> Add activity options to task seed code

- lib/api.js
- lib/decorators/enforcement-flags.js
- lib/decorators/index.js
- lib/hooks/create/index.js
- package-lock.json
- package.json
Needs:
- https://github.com/UKHomeOffice/asl-schema/pull/550
> Add decorator for enforcement flags

- lib/hooks/search/index.js
Then an enforcement case task resolves then send an update hook to the search indexer in order to refresh the index.
> Send enforcement updates to indexer on changes

- bin/profile-merge-log
- package-lock.json
- package.json
Needs:
- https://github.com/UKHomeOffice/asl-schema/pull/577
Will need write access allowing to the `profile_merge_log` table for workflow asl db user.
> Script for finding and logging profile merges

- lib/hooks/update-data/add-condition.js
- lib/hooks/update-data/index.js
- package-lock.json
- Sets reminder and condition data from payload
> Add conditions during PEL amendments

- package-lock.json
- package.json
update constants for 2024 bank hols & npm audit fix
> update constants for bank holidays

- lib/hooks/search/index.js
- lib/query-builders/filters/by-licence-type.js
- test/integration/task-lists/applicant.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4279
> ASL-4279 - Separate pil and pil-e/trainingPil filters

- seeds/data/refuse-ppl.js
See also https://github.com/UKHomeOffice/asl-schema/pull/605
> [ASL-4451] Add tasks for intent to refuse examples

- package-lock.json
- package.json
Update dependency asl-constants from 2.1.2 to 2.1.4; Update dependency asl-schema from 10.16.0 to 10.18.3; Update asl-workflow from 1.0.1 to 1.0.2
> Update dependency asl-constants from 2.1.2 to 2.1.4
