UKHomeOffice/asl-workflow

- .kube.dev.yaml
The resolver API will run with a self-signed cert, so we need to configure node to allow this.
> Allow self-signed certificates in downstream services

- .kube.dev.yaml
The secret wasn't created with consistent names to the other asl database, which is annoying and unexpected.
> Fix secret name

- lib/decorators/cacheable.js
- lib/decorators/index.js
Keeps references to any of the lookups by id done by decorators so that if the same lookup is performed twice in close succession then only a single database query is performed.
> Add caching support for decorator queries

- lib/flow/status.js
- lib/hooks/validate/payload.js
Once https://github.com/UKHomeOffice/taskflow/pull/20 is merged, Taskflow will capture any "comment" property of the request body into an activity log.
We should make the language consistent across workflow / taskflow / pages so that we always use comment in the data (we can alias it as "Reason" with labels or whatever).
> Rename reason to comment (more generic for taskflow)

- config.js
- lib/api.js
- lib/middleware/profile.js
The API attepts to create a profile if it can't find one, which involves a call to workflow. If workflow then tries to load the profile from the API then this causes an infinite recursive loop of the two APIs calling one another. That is bad.
Instead load the user's profile from the database directly on workflow requests.
> Load profile from database not API

- .drone.yml
- Dockerfile
- knexfile.js
- lib/api.js
- package-lock.json
- package.json
- scripts/migrate-test.js
- scripts/migrate.js
- seeds/data/cases.json
- test/data/default.js
- test/data/index.js
- test/helpers/asl-db.js
- test/helpers/taskflow-db.js
- test/helpers/with-user.js
- test/helpers/workflow.js
- test/integration/tasks.js
This adds support for running integration tests against workflow.
It uses the `taskflow-test` and `asl-test` (`workflow-asl-test` on `localhost`) databases.
> Tasklist integration tests

- lib/hooks/meta/default.js
- lib/hooks/meta/index.js
- lib/query-builders/asru.js
- lib/query-builders/index.js
- lib/query-builders/inspector.js
- lib/query-builders/licensing-officer.js
- lib/router/tasks.js
Refactors the query builder to move the code out of the main router, and makes the calling of query builders by progress step a little less repetitive.
Adds default metadata in metadata hook to expand any task that has a related profile or establishment irrespective of type.
Adds query builders for ASRU users.
> Add task list query builders for ASRU users + refactor

- lib/hooks/meta/default.js
Currently metadata is only added to 'create' tasks, which is incorrect. We need metadata to be bound to all tasks.
> Add metadata to all tasks

- lib/api.js
- lib/decorators/index.js
- lib/decorators/metadata.js
- lib/decorators/next-steps.js
- package-lock.json
- package.json
Not all decorators need to be applied in list view (and involve potentially expensive data operations when applied to a list), so split the decorators into separate modules to be able to configure which are applied to lists, and which are only for single-task requests.
> Optimise decorators

- lib/hooks/resolve/index.js
`update` sets the data to whatever is passed, it is not a patch operation, so the full model needs to be set when updating or it destroys all the other data.
> Don't destroy all the data when tasks resolve

- lib/hooks/notify/index.js
This just throws an error and makes a mess of the logs - in particular when running locally.
> Don't use notifcations hook if it's not configured

- lib/decorators/next-steps.js
- lib/query-builders/index.js
When a brand new user logs in for the first time then a profile does not exist in the database. We need to ensure that if this is the case then the call to create the new profile does not fail, and that a cal to get open tasks returns an empty list.
> Handle the case where no user profile exists

- lib/hooks/create/unique.js
- lib/hooks/meta/index.js
Tasks only have a status of "new" if the create hook fails in some way to prevent them autoforwarding. If that happens then consider them to be closed so that they don't block subsequent attempts to raise tasks on that entity.
Also bundles a small refactor to make the `modelData` update explicit rather than relying on object property manipulation and a  downstream call to `update`.
> Don't consider "new" tasks to be open

- lib/flow/get-next-steps-for-user.js
- lib/hooks/validate/status.js
In some circumstances it was returning a plain array, which then threw an error when trying to `.then` it.
> Ensure getNextStepsForUser always returns a promise

- lib/router/model-tasks.js
Establishments weren't returning any open tasks because the query was searching for a string id.
> Establishment ids are stored as ints

- lib/hooks/update-data/project.js
The declarations now reveal extra fields in some circumstances. Store that data against the task.
> Store extra declaration options in task metadata

- lib/middleware/resolve-project-version-updates.js
We recycle the resolver hook to perform this task, which expects to receive a fully fleshed out task model as an argument and be able to call methods on it. This is not the case here, so we need to provide a stub method.
> Pass a no-op patch method when autoresolving project version patch tasks

- lib/router/metrics.js
It shouldn't affect anything in prod, but some old tasks in preprod don't have full metadata and cause error if reading too far back in time.
> Use lodash.get for rading nested properties

- lib/router/metrics.js
The updatedAt timestamp doesn't actually work on tasks - it's always the same as the createdAt - so use the resolved event to get the closed timestamp for metrics.
> Use correct timestamps

- lib/query-builders/applicant.js
We were incorrectly setting the subject to the applicant meaning licence holders cannot action their own tasks.
This change ensures licence holders can see and action tasks to do with their own licences
> Include licence holders tasks

- lib/flow/index.js
Changing a profile amendment to no longer meet the criteria to raise a task results in an error because a resubmission cannot currently auto-resolve.
Reconfigure the allowed next steps to ensure resubmissions are always treated the same as new submissions.
> Allow resubmissions to autoresolve

- lib/decorators/cacheable.js
The cache was storing the query object itself rather than the query result, which meant that subsequent requests to access the cached query caused re-execution, and therefore exactly no performance benefit.
By adding the result of the query rather than the query to the cache we can drastically improve performance of task lists.
Also increase the cache timeout to 5 mnutes from 1 minute.
> Optimise decorator caching

- lib/query-builders/admin.js
- lib/query-builders/applicant.js
- lib/query-builders/ntco.js
The `whereNotIn` clause in a query can't hit the database indexes on the status column and so the queries run far slower than other task-list queries.
Replace the `whereNotIn` with a `whereIn` used in conjunction with a filter against a list of excluded statuses so that the indexes are used for the query.
> Replace whereNotIn queries with a whereIn

- lib/flow/index.js
- lib/router/model-tasks.js
Using `whereNotIn` prevents using indexes for the database query, so it runs slowly. Invert the status list and use a `whereIn` instead.
> Apply whereNotIn optimisation to model tasks

- lib/router/metrics.js
We only need to get the number of returns in the activity log, not load the entire log into memory. Optimise the query to create a far smaller dataset.
> Reduce amount of data returned by metrics query

- lib/api.js
- lib/decorators/activity-log.js
- lib/decorators/delete-comments.js
- lib/decorators/filter-comments.js
- lib/decorators/index.js
- test/unit/decorators/delete-comments.js
- test/unit/decorators/filter-comments.js
Removes comments based on the user role, the commenter's role and time relative to particular events. Users can always see comments made by people of the same "type" as them (i.e. ASRU or not-ASRU). For ASRU users viewing external comments they only become visible post-submission. For external users viewing ASRU comments they only become visible after an ASRU instigated status change.
Also moves the comment deletion code into here because it makes more sense.
> Filter comments from activity log

- lib/query-builders/admin.js
- lib/query-builders/filter-to-establishments.js
- lib/query-builders/index.js
- lib/query-builders/ntco.js
- test/integration/task-lists/establishment-admin.js
Because these do not get an `establishmentId` property set then they need a separate query clause to be able to be included in the establishment filter.
Refactor slightly to make this query a standard component.
> Include establishment tasks in establishment filter

- lib/decorators/filter-comments.js
- test/unit/decorators/filter-comments.js
The task that is created to create a new profile for a user does not have a profile attached, so if the decorator attempts to read properties from the profile on that task's activity then it throws errors.
Use `get` instead of direct property access to handle this case.
> Handle decorating cases with anonymous status changes

- lib/decorators/deadline.js
- test/unit/decorators/deadline.js
When recalled was added to the possible statuses it wasn't considered in the parameters that prevent tasks from having a deadline.
> Don't add deadline property to recalled tasks

- lib/hooks/create/pil.js
If a PIL amendment has been initiated by an ASRU user then don't send it via the NTCO for endorsement.
Also remove some database lookups that weren't required because the profile data was already present on the hook argument.
> Don't send ASRU initiated PIL amendments to NTCO

- lib/decorators/activity-log.js
This should make autoresolved things resolve a little quicker because it doesn't need to do the work to populate the log, and doesn't need to send the payload over the wire.
> Don't send an activity log for autoresolved tasks

- lib/query-builders/index.js
- lib/router/tasks.js
Returns the number of tasks before filters have been applied in order to return the unfiltered total to the user.
> Add secondary query to filtered task lists to get unfiltered total

- lib/hooks/create/pil.js
Otherwise user's who have previously been licensing officers, but no longer ASRU can autoresolve PILs.
> Ensure user is ASRU user before autoresolving

- lib/middleware/profile.js
User's without an existing profile (e.g. new invites, test users with no seeds) were throwing an error because `profile` is undefined.
> Check we have a profile before checking properties

- lib/decorators/next-steps.js
- lib/hooks/validate/status.js
- test/data/ids.js
- test/data/tasks.js
- test/integration/tasks/applicant.js
- test/integration/tasks/next-steps.js
If a project grant or update task is back with a user then force them down the journey of "edit and resubmit" rather than allowing direct resubmission.
The actual available next steps need to be as they are because when it eventually submits it submits with a status of "resubmitted" and so the validator needs to allow that.
> Suppress "resubmitted" option in project next steps

- lib/flow/get-next-steps-for-user.js
- test/data/ids.js
- test/data/profiles.js
- test/data/tasks.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
- test/integration/tasks/next-steps.js
The receiving admin on a PIL transfer cannot edit the request as the PIL is still owned by the original establishment until the task is approved. Remove the option to edit unless it's the applicant viewing the task.
> Remove edit and resubmit as next step option for admins on pil transfer

- lib/api.js
So we can filter 404s from legit errors.
> Send error statuses in error logs

- lib/messager/index.js
If a changelog record for a message is detected then read the content of the record and throw an error accordingly.
This allows any errors in the resolution of messages to be exposed back to the user immediately without needing to wait for a timeout.
> Detect errors from resolver written back to changelog

- lib/api.js
- lib/decorators/index.js
- lib/decorators/metadata.js
- lib/decorators/task-type.js
- test/unit/decorators/task-type.js
Add task type (application / amendment / transfer / revocation) to the returned task metadata.
This is to replace several repetitions of the same code in the UI:
https://github.com/UKHomeOffice/asl-pages/blob/master/pages/task/read/routers/read.js#L157-L180
https://github.com/UKHomeOffice/asl-pages/blob/master/pages/common/routers/success.js#L39-L47
https://github.com/UKHomeOffice/asl-pages/blob/master/pages/project/read/views/index.jsx#L82-L100
> Add the task type to the api response

- lib/hooks/meta/default.js
- lib/query-builders/index.js
- lib/query-builders/inspector.js
- lib/query-builders/licensing-officer.js
Establishment tasks don't send an `establishmentId` param on creation (just `id`) so it was not being copied to the task in the expected place for the queryBuilder to query on it.
> Show establishment tasks in "My Tasks" tab

- lib/query-builders/index.js
- test/integration/task-lists/error-states.js
If you request a task list with a broken progress parameter in the query string then it returns the default underlying query which returns _everything_ with no status filters (including autoresolved) which then breaks in the client.
Instead return an empty list immediately if the progress parameter doesn't make an expected value.
> Whitelist progress states in task list builder

- lib/router/profile-tasks.js
- test/integration/profile-tasks/index.js
Adds pagination to the endpoint and allows non-open tasks to be included in the results if a query string parameter is passed.
Also includes tasks opened by the user as well as about the user in the response. This is acceptable in terms of the impact on its other use in preventing profile mergers as we probably shouldn't allow mergers if there are open tasks created by a user anyway because it will mess with "return to applicant" functionality.
> Expand profile tasks endpoint

- lib/router/profile-tasks.js
- test/integration/profile-tasks/index.js
When passing an "all" flag to the profile tasks endpoint don't include autoresolved tasks.
> Exclude autoresolved tags from profile task list

- lib/flow/index.js
* flow.getNextSteps is returning a reference to the array from settings - we should clone this before mutating to avoid a memory leak
> Bugfix - dont mutate next steps from settings

- lib/hooks/meta/index.js
- test/integration/profile/update.js
Profile creation tasks don't have a `changedBy` (by definition) and so the database lookup based on that parameter fails.
> Only try to set ASRU flag on task if profile exists

- lib/hooks/create/unique.js
- package.json
- test/integration/establishment/conditions.js
PEL condition updates autoresolve, and can't conflict with an open task so can safely be disregarded when checking for conflicting tasks.
> Allow conditions updates to establishments when there is an open task

- test/unit/decorators/deadline.js
The old code was dependent of activity log records being ordered newest to oldest. The new code doesn't care and will return the right value whatever.
Add a test to ensure this continues to be the case.
> Add test to ensure deadline calculation is not sensitive to activity log ordering

- lib/router/metrics.js
Currently all PIL amendments and applications are grant tasks, so appear as applications in the performance dashboard.
Split them into applications and amendments by checking the current status.
> Separate PIL grant tasks into applications and amendments

- lib/decorators/deadline/index.js
- test/unit/decorators/deadline.js
If a task has no activity log attached then we load it to do the deadline calculation, but then weren't actually using the copy of the data which had activity to do the calculation, so it threw errors.
> Fix deadline calculation

- lib/router/metrics/project-sla.js
Was using an incorrect hard-coded status to calculate project application SLA metrics. Swap this out for the properly defined value.
> Fix status for project submission

- lib/router/metrics/project-sla.js
The correct separator for JSON sub-selecting is a `.` not a `:` past the top level field name.
Also the date filter was incorrectly filtering tasks.
> Fix PPL deadline metrics queries

- lib/hooks/recall/index.js
- test/unit/hooks/recall/index.js
We were only forking recalled/returned versions on grant tasks - updated to include transfer
> Bugfix - fork version on recall

- lib/hooks/resolve/index.js
- test/unit/hooks/resolve/index.js
* We were using the task id to inform the ui of the new version when forking, update the data.versionId instead
* Don't update id if there is already an id set
> Bugfix - dont update id post resolve

- lib/api.js
- lib/hooks/create/unique.js
- lib/hooks/update-action/index.js
- test/data/default.js
- test/data/ids.js
- test/data/tasks.js
- test/helpers/workflow.js
- test/integration/project/transfer.js
* Updated unique check to update project grant status to resubmitted if already present, point to existing record rather than creating a new task
* Added update-action hook, this updates the action type of a grant task if it is detected to be a transfer
> Feature - ppl transfer

- lib/hooks/create/unique.js
- test/data/ids.js
- test/data/tasks.js
- test/helpers/workflow.js
- test/integration/hooks/unique.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
- test/integration/task-lists/licensing.js
If a task is created and there is an existing task with a matching model and action, and in an editable state then automatically redirect to that task and update the data with the new payload.
> Redirect all matching tasks when resubmitting

- lib/flow/get-next-steps-for-user.js
- lib/query-builders/admin.js
- lib/query-builders/applicant.js
- test/data/ids.js
- test/data/tasks.js
- test/integration/profile-tasks/index.js
- test/integration/tasks/next-steps.js
Currently licence holders and admins can discard ASRU initiated tasks, this should not be possible.
Remove all possible next steps for a user if they are not an ASRU user and the task was ASRU initiated. Additionally remove the tasks from their outstanding task lists if they are ASRU initiated.
> Prevent external users actioning ASRU tasks

- lib/decorators/activity-log.js
- lib/decorators/filter-comments.js
- package-lock.json
- package.json
- test/helpers/history.js
- test/unit/decorators/activity-log.js
- test/unit/decorators/filter-comments.js
* only include status change events and deadline updates
~* if multiple events happened within 5 secs, group taking the action from the first event, and the status from the last~
* check the status change sent in the request, if the end status of the activity log item doesn't match then group with the next item and show the status sent (action) and the end status (status)
> bugfix - activity log

- lib/messager/index.js
The first query _never_ returns a match as it is performed immediately after sending the message. Add an initial wait before checking the changelog for the first time.
Also refactor the promises to be a bit cleaner by extracting the `wait` into a separate function.
> Remove first query to changelog when polling

- lib/flow/status.js
- package.json
- test/data/default.js
- test/data/ids.js
- test/integration/role/holc.js
- test/unit/hooks/create/role.js
The check for moving things into "resolved" status was only testing if the task was creating a HOLC, but removing a HOLC should also resolve.
Allow both create and delete actions on HOLC roles to resolve.
> Allow removing HOLCs

- lib/flow/status.js
- lib/hooks/model-data/index.js
- test/integration/role/delete.js
- test/integration/role/holc.js
This was not previously being set on tasks, but is needed to handle the UI for removing multiple roles at the same time.
> Set modelData when deleting roles

- lib/query-builders/asru.js
- test/data/tasks.js
- test/helpers/assert-tasks.js
- test/helpers/taskflow-db.js
- test/integration/related-tasks/index.js
- test/integration/task-lists/applicant.js
- test/integration/task-lists/asru.js
- test/integration/task-lists/establishment-admin.js
- test/integration/task-lists/inspector.js
It was not specifying the id correctly for `discarded-by-asru`.
Refactor task tests so that they better assert on tasks which are not present in a result set.
> Fix query builder for generic ASRU user

- lib/hooks/create/project.js
- test/data/default.js
- test/data/ids.js
- test/unit/hooks/create/project.js
These should leave a visible record, so need to be resolved rather than autoresolved.
> Mark LO PPL revocations as resolved

- lib/middleware/profile.js
- lib/router/tasks.js
- test/data/default.js
- test/data/profiles.js
- test/helpers/asl-db.js
Don't eager load ASRU establishment assignments onto profiles by default. These are quite large objects, which use a lot of space on the profile and are saved on every activity, where tehy're onyl actualyl used for loading task lists.
Instead only load ASRU users establishment assignments when building a task list.
Also remove access token from the user, since it isn't used downstream and while it represents only a very mild security risk since it is short-lived, it has no business being saved to data.
> Optimise activity log data payloads

- lib/hooks/create/unique.js
- test/helpers/asl-db.js
Use a `whereIn` instead of a `whereNotIn` for finding open tasks. This offers vastly improved performance because it facilitates the use of the index on task status.
> Improve performance of task uniqueness check

- .eslintrc
- config.js
- lib/api.js
- lib/hooks/search/index.js
- lib/middleware/profile.js
If a task relating to a profile, project or establishment completes then trigger a request to the search service to re-index the record.
Note: not waiting on any code changes, but probably doesn't need to ship until we have search working at least on preprod.
> Add hook to re-index search when entity changes

- lib/hooks/search/index.js
Otherwise the assignments shown in the search results will not be accurate until the next time the indexer runs.
> Refresh establishment search index when ASRU assignments change

- lib/api.js
- lib/hooks/resolution-meta/index.js
We want to play back the remaining roles of the same type which were still assigned at the establishment at the moment the task was completed.
> Add remaining roles to task meta on role delete

- lib/decorators/deadline/get-deadline.js
- lib/hooks/create/project.js
- test/data/default.js
- test/data/ids.js
- test/integration/project/continuation.js
- test/unit/hooks/create/project.js
Instead of skipping the endorsement step for PPL amendments send all PPL grant tasks to admins for endorsement unless they're initiated by ASRU users.
> Send PPL amendments for endorsement

- lib/decorators/normalise-training.js
- test/unit/decorators/normalise-training.js
Adding the result of a reduce on an empty array meant that the certificates were always appended with `{}` if no exemptions are present.
Return early if there are no exemptions and don't add a record to the certificates.
> Prevent adding empty exemption if none exist

- lib/hooks/search/index.js
Both of these will change the search index in ways which are not currently refreshed. Ensure that the search index stays up to date for both profiles in a merger, and adds the new licence number when granting a PIL.
> Update search index on profile merges and PIL grants

- lib/hooks/create/unique.js
- test/integration/hooks/unique.js
The `establishmentId` property was being reset to the originating establishment when resubmitting PPL transfers, which when eventually resolved resulted in broken PPL states.
When patching the data on a task resubmission do not overwrite the establishment id.
> Preserve establishment id when resubmitting PPL tasks

- bin/deadline-has-passed
- lib/router/deadline-passed.js
We need the deadline at the time the deadline was passed, as the deadline object may disappear if the task is returned to the applicant.
> Store deadlinePassedDate as a separate property on the task so it doesn't get removed

- bin/add-deadlines-to-legacy-tasks
The `.orWhereRaw("data->'deadline'->>'standard' is null")` condition was added to "fix" the tasks on preprod that were left without dates the first time we ran the script.
This is no-longer the case so let's get rid of this extra condition and make doubly sure we don't overwrite any existing deadline objects.
> Make sure we don't touch any existing deadline objects

- seeds/data/cases.json
This seed should now include the flags added by the deadline migration scripts which were previously left out to test the scripts.
> Seed was prev set up to test deadline scripts

- lib/decorators/activity-log.js
- lib/decorators/licence-holder.js
- lib/hooks/model-data/index.js
When a task to change PPL holder is closed the "before" state for the licence holder disappears if the task was created before the change to populate `modelData` shipped.
In this case add a decorator to populate the `modelData.licenceHolder` on the submission activity.
Additionally add the email to the `modelData` population hook because this is normally rendered but looks a bit odd when it disappears on completion.
> Fix "before" state for completed PPL holder changes

- lib/decorators/activity-log.js
Rendering a task fails if there is no associated activity. Sometimes we need to be able to render autoresolved tasks, so allow them to serve their activity log if requested.
> Serve activity log on autoresolved tasks

- lib/api.js
This allows PPL applications to appear in search once they are submitted to ASRU
> Re-index search when submitting tasks

- lib/hooks/create/unique.js
If there is an open profile amendment task and the user verifies their email (or more likely logs in with email already verified in keycloak and so auto-verifies) then don't block the task.
> Don't enforce uniqueness of tasks for email verification actions

- lib/hooks/notify/index.js
`r2` doesn't implement promises as expected.
> Fix broken promise

- lib/hooks/search/index.js
The search re-index hook is set up to fire on task submission to ASRU (to handle draft PPL submissions) however entity creation tasks don't have an id at this point and result in an error in the search indexer.
Ignore anything that doesn't have an id and don't try to index it.
> Don't attempt to re-index objects with undefined id

- lib/hooks/search/index.js
The profile search was showing establishment associations after they were removed. Trigger a profile re-index when associated perms are changed.
> Update search index on perms change

- lib/api.js
There's _a lot_ of 403s for related tasks which we don't really care about in the logs. The basic logging is fine for 4xx range errors.
> Don't log errors for 4xx range

- .drone-1.0.yml
- lib/util.js
- test/unit/hooks/create/project.js
The `canEndorse` function was throwing an error because it did not expect to be called with an ASRU user's profile - and therefore have no establishments.
> Fix RA submission by ASRU users

- lib/hooks/create/establishment.js
- test/unit/hooks/create/establishment.js
This prevents updates to cjsm email etc being included in metricsl
> Bugfix - autoresolve updates to non licenced fields for pel

- lib/query-builders/filters/by-is-amendment.js
This was stopping anything other than trainingPils displaying in the metrics taskslists.
> PIL applications have modelData.status pending not inactive

- lib/query-builders/filters/by-is-amendment.js
Some of the PIL applications counted on the summary page are re-activations of revoked PILs (modelData.status = 'revoked') but we were excluding these from the tasklist.
> Just use not already active for applications

- lib/router/related-tasks.js
- test/data/tasks.js
The project related tasks query started an "or" query context, which meant that the status filters were included in the "or" instead of the "and" that they were expected to be in.
Instead create a new context for the "or" clauses to contain those.
> Exclude autoresolved project tasks from related tasks

- lib/decorators/activity-log.js
* If decorator doesn't find a profile for assigned to, dont default to empty object
> Tweak - dont include null assignedTo

- lib/decorators/activity-log.js
- package-lock.json
- package.json
- scripts/discard-expired-projects.js
Once a PPL has expired then amendments and transfers that might be in progress should be discarded.
This adds a script which will run as a nightly cron to do that.
> Discard tasks related to expired PPLs

- lib/router/related-tasks.js
When checking if a user can be removed from an establishment, we don't care about tasks that the user has endorsed (or some other interaction) if they are not the owner of the licence itself.
> Allow fetching of tasks owned by the profile

- lib/decorators/activity-log.js
If an auto-unassignment is triggered by an assigned task changing status, then the status of the previous activity log item was being overwritten with "assign" which caused the task status in the task view to always display "Task Assigned" whenever this happened (including on task resolution).
> Prevent task status label getting overwritten by assign

- lib/decorators/filter-comments.js
- test/unit/decorators/filter-comments.js
* if a task is recovered, ignore this when working out if a comment is new or not
> Bugfix - recovered comments

- lib/query-builders/filters/by-ppl-type.js
RA tasks should not display if the user has filtered to "Applications" or "Amendments", so exclude them by requiring a `grant` action (since RA tasks have a `grant-ra` action).
Also add new filter for PPL revocation tasks.
> Filter out RA tasks from PPL application filters

- lib/query-builders/filters/by-ppl-type.js
Continuation is only relevant for first-time applications and not amendments, so exclude amendments from the list when filtering to continuations.
> Remove PPL amendments from continuations filter

- lib/hooks/endorsed/pil.js
- package-lock.json
- package.json
- test/helpers/database-settings.js
- test/helpers/history.js
- test/unit/hooks/endorsed/pil.js
If a PIL task has been previously referred to an inspector then when it is resubmitted (endorsed) then it should be directed back to an inspector and not sent to licensing.
> Update PIL endorsed hook to preserve inspector referral

- lib/hooks/endorsed/pil.js
- test/unit/hooks/endorsed/pil.js
If a PIL task is referred to an inspector, and then returned, then when it is endorsed it gets passed directly to the inspectorate by setting the status to `with-inspectorate`.
If this same task is then returned / recalled a second time, the last ASRU status will be `with-inspectorate` so we need to check for this as well.
> if returned PIL was with inspectorate return to inspectorate

- seeds/helpers/create-task.js
- seeds/tables/cases.js
Only works for project grant at the moment, but it looks up the actual project data and populates a best effort of what a task and activity log would look like for an application submission.
This seems easier than hard-coding everythign manually.
This particular instance won't work until https://github.com/UKHomeOffice/asl-schema/pull/532 is merged.
> Add helper for generating realistic task data from minimal input

- lib/hooks/create/project.js
Previously the training profile was only saved to the version at the point of submission to ASRU, so when an admin user was reviewing an application for endorsement it would always show as having no training record.
> Save applicant's training profile at the point of submission for endorsement

- lib/api.js
- package-lock.json
- package.json
- test/data/default.js
- test/data/ids.js
- test/integration/hooks/deadlines.js
- test/integration/hooks/model-data.js
- test/integration/project/update-licence-holder.js
Adding the integration tests for deadlines meant setting the project statuses in the seeds to appropriate values, which had some interesting side-effects - in particular a test that was effectively noop-ing for changing licence holders on stub licences because all the projects were `inactive`.
> Add internal deadline hook and integration test

- lib/decorators/deadline/index.js
- lib/hooks/set-internal-deadline/index.js
- seeds/data/internal-deadline-cases.js
- test/unit/hooks/set-internal-deadline/index.js
The task list endpoint now has the active deadline populated by the query itself, but the route to fetch an individual task is in `taskflow` not `asl-workflow` hence the decorator rather than modifying the query.
> decorate task with active deadline

- bin/discard-expired-projects
Somehow on preprod there's a project task where a corresponding project doesn't exist, so this script fails with an error.
> Check project exists to prevent accessing property of undefined

- package.json
There are some tasks wih expired deadlines that are not seeded as expired, but are ignored by the reports because the flags are added as a nightly cron.
When seeding data run the script immediately so all tasks are flagged.
> Mark deadlines as passed after seeding

- lib/query-builders/index.js
There is an issue in postgres where queries with `limit` defined can run very slowly when sorted by an indexed column because they do a full scan rather than optimising the query.
Adding an arbitrary second sort parameter will resolve the issue.
Details: https://stackoverflow.com/questions/21385555/postgresql-query-very-slow-with-limit-1
> Add redundant secondary sort order to query builder

- lib/router/tasks.js
The concept of ASRU staff having associated establishments is no longer used, and the associations are no longer used downstream in the query builder, so there is no need to load them here.
> Remove lookup of associated establishments

- seeds/data/refuse-ppl.js
- seeds/helpers/create-task.js
Couldn't see an easy way to leave the licenceHolder property in the task data blank so passing through a flag in the opts to not include it.
> ASL-4082 - task seed for licence with no licenceHolder in DB

- lib/hooks/clear-deadline/index.js
The presence of the `removedDeadline` property prevents returned and resubmitted PPL tasks from correctly displaying their statutory deadlines when resubmitted.
Clear the `removedDeadline` property as well when returning a PPL to the applicant.
> Clear removed deadline from tasks when returning

- lib/hooks/create/pil.js
Since inspectors can now grant PIL applications, it doesn't make any sense that if they make an amendment directly that it has to go to a licensing officer for approval.
Allow inspector initiated PIL amendments to be granted directly.
> Allow inspectors to edit PILs directly

- lib/hooks/create/pil.js
The process to amend PILs was changed last week to allow inspectors to not need to go via licensing, but revocations were missed.
Also allow inspectors to revoke PILs directly.
> Allow inspectors to revoke PILs directly
